### ISSUE TITLE
missing shared library

### ISSUE THREAD

**Issue by ProfBird** [headmelted/codebuilds#3]
I installed vscode on my ODroid C2 using the Debian install script. The script completed successfully, but when I try to run vscode from the command line I get this error:

odroid@odroid64:~$ code-oss
/usr/share/code-oss/bin/../code-oss: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory

**Comment by headmelted** [comment]
Hi,

Which version of Debian are you using?

I've added the libXtst6 package to the dependencies list and I'm rebuilding now. I'll update this thread when the build has been deployed. If you can test then and let me know if it solves the problem for you that would be great.

Alternatively:

sudo apt-get install -y libxtst6

Should take care of it, then retry the installation after the above completes. Thanks for reporting this!

**Comment by ProfBird** [comment]
Thanks for the quick response! I'm running Ubuntu 16.04 on an ODroid C2. 
I'll try reinstalling as soon as you're build is ready.

-Brian

**Comment by headmelted** [comment]
Hi,

The update is available now.  Can you try installing again?

I have a couple of other ideas if that doesn't work for you, but im hopeful this should resolve it!

**Comment by ProfBird** [comment]
I ran the installation script again, but still have the same problem.
I also directly installed libxtst6, but that didn't solve the problem. When I try to run code-oss I still get this error message:
/usr/share/code-oss/bin/../code-oss: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory

**Comment by headmelted** [comment]
Can you try just installing libxtst in that case?

(sudo apt-get install -y libxtst)?

Its hard without seeing it in front of me, but if that doesn't work I'll
try to recreate your setup later today.

**Comment by ProfBird** [comment]
I gave that a try and now I get this error message:
/usr/share/code-oss/bin/../code-oss: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory

**Comment by ProfBird** [comment]
I just noticed that there was an error message while running the install script. Maybe it's a clue? Here it is:

Installing headmelted repository...
Repository install complete.
Updating APT cache...
Ign:1 https://dl.bintray.com/headmelted/deb-code-oss wheezy InRelease
Get:2 https://dl.bintray.com/headmelted/deb-code-oss wheezy Release [2,688 B]
Err:3 https://dl.bintray.com/headmelted/deb-code-oss wheezy Release.gpg
  404  Not Found
Hit:4 http://ports.ubuntu.com/ubuntu-ports xenial InRelease                    
Hit:5 http://ports.ubuntu.com/ubuntu-ports xenial-updates InRelease            
Hit:6 http://ports.ubuntu.com/ubuntu-ports xenial-backports InRelease          
Hit:7 http://ports.ubuntu.com/ubuntu-ports xenial-security InRelease           
Hit:8 http://ports.ubuntu.com/ubuntu-ports xenial-proposed InRelease           
Hit:9 http://deb.odroid.in/c2 xenial InRelease                                 
Hit:10 http://ppa.launchpad.net/saiarcot895/myppa/ubuntu xenial InRelease
Reading package lists... Done                      
E: The repository 'https://dl.bintray.com/headmelted/deb-code-oss wheezy Release' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Done!

**Comment by headmelted** [comment]
Thanks for updating with this.

I'm not sure what came unglued with the deb signing, but that's been patched up now.

In any case, I don't think it's related to the problem you're seeing.

The closest issue I could find is this:

http://stackoverflow.com/questions/17355863/cant-find-install-libxtst-so-6

Which sounds like a problem with the installed JRE?  It seems very unlikely that your setup would be trying to pull an Intel lib for this, but it *might* help to try running:

sudo apt-get install -y libxtst6:armhf

Which would force the ARM libs, although I think this is clutching at straws.  If that doesn't work for you I'll do some more digging.

**Comment by ProfBird** [comment]
I tried installing the "straw" and re-running the installation script. Not a fux. Thanks for persevering!

**Comment by headmelted** [comment]
There have been a series of improvements in the upstream code around dependency lists (they are a lot more extensive than they were). I need to extrapolate these out from intel to armhf but I don't anticipate this being a big job. I would *hope* this will take care of this issue for good.

**Comment by headmelted** [comment]
I haven't forgotten about this, I've just had my hands full with a big update.

More news soon, but if that update doesn't fix your issues, I'll get you to dump me some logs and roll up the slieves.  I will get you back up and running one way or the other, if you're still interested in these builds that is. :-)

**Comment by ProfBird** [comment]
$(UThanks. I've been working on other things, but I'll get back to this and give it a try soon! 

Brian


Brian Bird
Faculty
Computer Information Technology
http://www.lanecc.edu/cit
Lane Community College
Building 19, Room 152
4000 E. 30th Ave., Eugene, OR 97405

http://birdsbits.wordpress.com



>>> Jay Rodgers <notifications@github.com> 5/4/2017 1:48 AM >>>

I haven't forgotten about this, I've just had my hands full with a big update. 
More news soon, but if that update doesn't fix your issues, I'll get you to dump me some logs and roll up the slieves. I will get you back up and running one way or the other, if you're still interested in these builds that is. :-)

**Comment by crossan007** [comment]
I had to run ```apt-get install libxss1``` on ubuntu 16.04 (running on android via Linux Deploy)

**Comment by headmelted** [comment]
Thanks for this, libxss1 now added as a dependency.

**Comment by headmelted** [comment]
Folks, can I ask you to confirm if the latest releases resolve your issues as soon as you get a chance?

(Trying to close out any tickets that are resolved so I can see what still needs done).

Thanks!

**Comment by headmelted** [comment]
Going to close this out for now as I haven't heard anything in some time.  Please re-open if the added dependency doesn't solve this for you guys.
